[package]
name = "pollen_server"
version = "0.1.0"
authors = ["KerDelos <damien.delmas@etu.utc.fr>"]

[dependencies]
ws = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "*"

[dependencies.rusqlite]
version = "0.11.0"
features = ["bundled"]